### ISSUE TITLE
Request error not returned

### ISSUE THREAD

**Issue by dgg** [rse/mqtt-json-rpc#2]
If a method is registered and the body throws (that is, there was an error in the remote procedure) and JSONRPC error is never not sent back to the caller.

Instead, what happens is that the call eventually times out and the caller is none the wiser about the error, it appears as a communication error (because the receiver of the call never sent the response message).

I will try to submit a patch later in the day, but the error is in line 147 of _mqtt-json-rpc.js_: the `then()` handler is only called when the promise resolves, not when it is rejected. Using the `finally()` handler would not work either as its executor does not take any value 😞

**Comment by dgg** [comment]
It turns out I was wrong and the reason why errors are not propagated to the caller is because some mistake when using the JSONRPC library that generates the messages, in particular generating the error messages with `JSONRPC.error()`.

When generating an error message the second argument has to be of type `JSONRPC.JsonRpcError`. I will crate a PR to solve this issue.

**Comment by dgg** [comment]
Any progress on this one and the associated PR: #3 ?

**Comment by rse** [comment]
Fix now finally merged. Sorry for the long delay.
