### ISSUE TITLE
how to fix "error..Error: register: method "example/hello" already registered"

### ISSUE THREAD

**Issue by 18554852685** [rse/mqtt-json-rpc#4]
How to tell if method is registered？ thx

**Comment by rse** [comment]
There is currently no dedicated method for checking it, put you could use ```if (!mqtt.registry["example/hello"]) mqtt.register("example/hello", () => ...)``` if it is important to your code-flow.

**Comment by rse** [comment]
Now there is a registered method in the next version for you, too.
